#!/usr/bin/env bash
# Colossul multi-seat provisioner.
#
# Runs once at instance boot (via the colossul-provision supervisor unit) and
# is safe to re-run by hand: `colossul-seats provision`.
#
# Responsibilities, in order:
#   1. Discover the base image's ComfyUI install and Python.
#   2. Fetch/update the Storyrendr source into persistent /workspace.
#   3. Build it ONCE — one venv, one node_modules, one dist/ shared by all seats.
#   4. Install the Colossul custom nodes into the shared ComfyUI.
#   5. Materialise per-seat data directories.
#   6. Generate and start N GPU-pinned supervisor seat units.
#
# Seats share immutable things (code, models, custom nodes) and own mutable
# things (ComfyUI input/output/user/temp, backend outputs + SQLite databases),
# so four employees never collide while only one copy of the heavy assets
# exists on disk.
set -euo pipefail

# Resolve the shared lib from the installed location, falling back to the repo
# layout so provisioning logic can be exercised without building the image.
_LIB="${COLOSSUL_LIB:-/opt/colossul}/lib/common.sh"
[ -f "$_LIB" ] || _LIB="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"
# shellcheck source=lib/common.sh
source "$_LIB"

# Template variables reach us via /etc/environment, not necessarily through
# supervisord's inherited environment. Must happen before reading GITHUB_TOKEN.
load_vast_environment

# supervisord starts before vast.ai runs PROVISIONING_SCRIPT/MANIFEST. Let that
# finish first so model downloads and our build don't compete for disk and net.
wait_for_provisioning "Colossul provisioning"

SEAT_COUNT="$(num_seats)"
STORYRENDR_REPO="${STORYRENDR_REPO:-https://github.com/WASasquatch/storyrendr-services.git}"
STORYRENDR_REF="${STORYRENDR_REF:-main}"
STAMP_FILE="$COLOSSUL_ROOT/.provision-stamp"

echo ""
log "=============================================="
log " Colossul multi-seat provisioning — $SEAT_COUNT seat(s)"
log "=============================================="

# Refuse to build a layout that would crash-loop against a base-image service
# (ComfyUI 18188, its API wrapper 18288, jupyter 18080, ...).
if ! assert_no_reserved_collisions "$SEAT_COUNT"; then
    die "NUM_SEATS=$SEAT_COUNT allocates a port already used by the base image.
       Reduce NUM_SEATS, or edit the port math in lib/common.sh.
       Reserved: $RESERVED_PORTS"
fi

mkdir -p "$COLOSSUL_ETC" "$COLOSSUL_ROOT" "$SEATS_DIR" "$(dirname "$SRC_DIR")"
mkdir -p /var/log/portal 2>/dev/null || true   # cosmetic; never fatal

# Fail early and clearly if a build tool is missing, rather than 15 minutes
# later inside npm with an error that doesn't name the real problem.
missing=""
for tool in git uv node npm ffmpeg; do
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
done
[ -z "$missing" ] || die "required tool(s) not found:$missing
       These are baked into the image, so this usually means the template
       overrode the entrypoint or the image was built from an unexpected base."

# ─────────────────────────────────────────────────────────────────────────────
# 1. Discover ComfyUI
# ─────────────────────────────────────────────────────────────────────────────
log "Locating ComfyUI in the base image..."
COMFYUI_HOME="$(detect_comfyui_home || true)"
[ -n "$COMFYUI_HOME" ] || die "Could not find a ComfyUI install (no main.py beside a comfy/ package under /workspace or /opt).
       Set COMFYUI_HOME explicitly in the Vast template and restart the instance."

COMFYUI_PYTHON="$(detect_comfyui_python "$COMFYUI_HOME" || true)"
[ -n "$COMFYUI_PYTHON" ] || die "Could not find a Python interpreter for ComfyUI. Set COMFYUI_PYTHON explicitly."

log "  ComfyUI  : $COMFYUI_HOME"
log "  Python   : $COMFYUI_PYTHON"
if ! "$COMFYUI_PYTHON" -c 'import torch' >/dev/null 2>&1; then
    warn "  torch is NOT importable with $COMFYUI_PYTHON — ComfyUI seats will likely fail to start."
fi

cat > "$RUNTIME_ENV" <<EOF
# Generated by provision.sh — do not edit by hand.
COMFYUI_HOME=$COMFYUI_HOME
COMFYUI_PYTHON=$COMFYUI_PYTHON
NUM_SEATS=$SEAT_COUNT
EOF

# ─────────────────────────────────────────────────────────────────────────────
# 2. Retire the stock single-instance services
#
# The Dockerfile renames their config files, but if the base image ever ships
# them under names we didn't match they would still be running:
#   comfyui     — a 5th ComfyUI competing for VRAM on GPU 0
#   api-wrapper — a serverless shim bound to 18288, and pointed at that ComfyUI
# Stopping by name at runtime closes that gap.
# ─────────────────────────────────────────────────────────────────────────────
for stock in comfyui api-wrapper; do
    if supervisorctl status "$stock" >/dev/null 2>&1; then
        warn "Stock '$stock' service is still registered — stopping it."
        supervisorctl stop "$stock" || true
    fi
done

# Announce the control panel the moment its tunnel exists (usually seconds in),
# so the operator has something clickable during the 10-20 minute build instead
# of a spinner. Backgrounded: a rate-limited tunnel must not delay the build.
( print_early_access 60 | access_log_tee --append ) &

# ─────────────────────────────────────────────────────────────────────────────
# 3. Fetch the Storyrendr source
# ─────────────────────────────────────────────────────────────────────────────

# Normalise an SSH remote to HTTPS so token auth works.
case "$STORYRENDR_REPO" in
    git@github.com:*) STORYRENDR_REPO="https://github.com/${STORYRENDR_REPO#git@github.com:}" ;;
esac

# Feed the token through a credential helper instead of embedding it in the
# remote URL, so it never lands in .git/config or in git's stderr on failure.
git_auth() {
    if [ -n "${GITHUB_TOKEN:-}" ]; then
        git -c credential.helper= \
            -c "credential.helper=!f() { echo username=x-access-token; echo password=\$GITHUB_TOKEN; }; f" \
            "$@"
    else
        git "$@"
    fi
}

if [ -d "$SRC_DIR/.git" ]; then
    log "Updating existing source checkout ($STORYRENDR_REF)..."
    if git_auth -C "$SRC_DIR" fetch --depth 1 origin "$STORYRENDR_REF"; then
        # reset --hard, NOT checkout. We patch vite.config.ts in the working
        # tree, so the tree is always dirty; `git checkout` refuses to overwrite
        # a modified file and provisioning would only warn — leaving the
        # instance silently running old code. The tree is disposable: the patch
        # is re-applied below, and node_modules/.venv/dist are untracked so
        # reset does not touch them.
        git -C "$SRC_DIR" reset --hard -q FETCH_HEAD \
            || warn "Could not reset to FETCH_HEAD — continuing with the existing checkout."
    else
        warn "git fetch failed — continuing with the existing checkout."
    fi
else
    if [ -z "${GITHUB_TOKEN:-}" ]; then
        die "storyrendr-services is a private repository and no GITHUB_TOKEN was provided.
       Add GITHUB_TOKEN=<a PAT with repo:read> to the Vast template environment and restart."
    fi
    log "Cloning $STORYRENDR_REPO @ $STORYRENDR_REF ..."
    git_auth clone --depth 1 --branch "$STORYRENDR_REF" "$STORYRENDR_REPO" "$SRC_DIR" \
        || die "Clone failed. Check GITHUB_TOKEN scope and that STORYRENDR_REF ('$STORYRENDR_REF') exists."
fi

log "Initialising submodules (VNCCS_Utils / Pose Studio)..."
git_auth -C "$SRC_DIR" submodule update --init --recursive --depth 1 \
    || warn "Submodule init failed — Pose Studio will be unavailable."

SRC_SHA="$(git -C "$SRC_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"
log "  Source at $SRC_SHA"

BACKEND_DIR="$SRC_DIR/colossul-backend"
FRONTEND_DIR="$SRC_DIR/colossul-frontend"
[ -d "$BACKEND_DIR" ]  || die "Expected $BACKEND_DIR in the checkout — is STORYRENDR_REF correct?"
[ -d "$FRONTEND_DIR" ] || die "Expected $FRONTEND_DIR in the checkout — is STORYRENDR_REF correct?"

# ─────────────────────────────────────────────────────────────────────────────
# 4. Build once, share across seats
#
# Skipped when the commit is unchanged and prior build artefacts survive in
# persistent /workspace, so a plain instance restart comes up in seconds.
# ─────────────────────────────────────────────────────────────────────────────
NEED_BUILD=1
if [ "${FORCE_REPROVISION:-0}" != "1" ] \
   && [ -f "$STAMP_FILE" ] \
   && [ "$(cat "$STAMP_FILE" 2>/dev/null)" = "$SRC_SHA" ] \
   && [ -x "$BACKEND_DIR/.venv/bin/python" ] \
   && [ -d "$FRONTEND_DIR/node_modules" ] \
   && [ -f "$FRONTEND_DIR/dist/index.html" ]; then
    NEED_BUILD=0
    log "Build is current for $SRC_SHA — skipping (FORCE_REPROVISION=1 to rebuild)."
fi

# Applied on EVERY provision, not just when rebuilding. vite.config.ts is read
# by the preview server at runtime, and the `reset --hard` above wipes the
# patch — so skipping it on a no-change re-provision would leave every seat
# proxying /api to the stock 127.0.0.1:8189, which nothing listens on. The
# patch is idempotent, so re-running costs nothing.
log "Patching the frontend to accept a per-seat backend URL..."
"$COMFYUI_PYTHON" "$COLOSSUL_LIB/patches/patch_vite_backend_url.py" "$FRONTEND_DIR/vite.config.ts" \
    || die "vite.config.ts patch failed — see the error above. The upstream proxy target may have changed."

if [ "$NEED_BUILD" = "1" ]; then
    log "Syncing the backend virtualenv (uv sync)..."
    ( cd "$BACKEND_DIR" && uv sync ) || die "uv sync failed in $BACKEND_DIR"

    # Pose Studio's SAM3D extras pull torch into the backend venv. Multi-GB and
    # slow, but it lands in persistent /workspace and only happens once.
    if [ "${SKIP_VNCCS_EXTRAS:-0}" = "1" ]; then
        log "SKIP_VNCCS_EXTRAS=1 — skipping SAM3D extras (Pose Studio pose extraction will 503)."
    elif [ -f "$BACKEND_DIR/scripts/ensure_vnccs_extras.py" ]; then
        log "Installing SAM3D extras (one-time, large — set SKIP_VNCCS_EXTRAS=1 to skip)..."
        ( cd "$BACKEND_DIR" && ./.venv/bin/python scripts/ensure_vnccs_extras.py ) \
            || warn "SAM3D extras incomplete — Pose Studio pose extraction may 503."
    fi

    log "Installing frontend dependencies..."
    if [ -f "$FRONTEND_DIR/package-lock.json" ]; then
        ( cd "$FRONTEND_DIR" && npm ci ) || die "npm ci failed in $FRONTEND_DIR"
    else
        ( cd "$FRONTEND_DIR" && npm install ) || die "npm install failed in $FRONTEND_DIR"
    fi

    # Mirror start.sh's _migrate_comfyui_workflows. On branches that ship the
    # graph workflows only at the repo root (a --no-workflows deploy), the UI's
    # ComfyUI tab has nothing to load unless they are copied into public/ before
    # the build. A no-op when the frontend already carries a manifest.
    if [ -d "$SRC_DIR/comfyui_workflows" ] && [ ! -f "$FRONTEND_DIR/public/workflows/comfyui/manifest.json" ]; then
        log "Migrating ComfyUI graph workflows into the frontend..."
        dst="$FRONTEND_DIR/public/workflows/comfyui"
        mkdir -p "$dst"
        manifest="{" first=1
        for f in "$SRC_DIR"/comfyui_workflows/*.json; do
            [ -f "$f" ] || continue
            fname="$(basename "$f")"
            cp "$f" "$dst/$fname"
            # "1_Animatics_....json" -> "step1"
            num="$(printf '%s' "$fname" | sed -n 's/^\([0-9]\+\)_.*/\1/p')"
            [ -n "$num" ] || continue
            [ "$first" = "1" ] && first=0 || manifest="$manifest,"
            manifest="$manifest
  \"step$num\": \"$fname\""
        done
        printf '%s\n}\n' "$manifest" > "$dst/manifest.json"
        log "  migrated $(find "$dst" -name '*.json' | wc -l) workflow file(s)"
    fi

    # VITE_COMFYUI_EMBED is the only build-time flag the client reads, and it is
    # identical for every seat — so a single dist/ serves all of them. The
    # per-seat ComfyUI/backend URLs are read by the preview server at runtime.
    log "Building the frontend (shared by all seats)..."
    BUILD_LOG="$COLOSSUL_ROOT/.frontend-build.log"
    if ! ( cd "$FRONTEND_DIR" && VITE_COMFYUI_EMBED=true npm run build ) 2>&1 | tee "$BUILD_LOG"; then
        # "Cannot find module '@/...'" on a *fresh clone* almost never means a
        # genuine code error — it means the file exists on a developer's disk
        # but was never committed, usually because a broad .gitignore rule
        # (e.g. a bare `lib/`, which git matches at any depth) swallowed it.
        # Say so, because "build failed" alone sends people hunting in the
        # wrong repository.
        if grep -q "Cannot find module '@/" "$BUILD_LOG" 2>/dev/null; then
            warn ""
            warn "The build failed on modules that are MISSING FROM THE REPOSITORY:"
            grep -o "Cannot find module '@/[^']*'" "$BUILD_LOG" | sort -u | sed 's/^/       /' >&2
            warn ""
            warn "These files most likely exist on a developer's machine but were never"
            warn "committed - a .gitignore rule is hiding them. In storyrendr-services:"
            warn "       git check-ignore -v colossul-frontend/src/lib/output-utils.ts"
            warn "A bare 'lib/' or 'build/' rule matches directories at ANY depth."
            warn "Fix: anchor the rule ('/lib/'), 'git add -f' the missing files, push,"
            warn "then re-run: colossul-seats provision"
            warn ""
        fi
        die "Frontend build failed in $FRONTEND_DIR (full log: $BUILD_LOG)"
    fi

    echo "$SRC_SHA" > "$STAMP_FILE"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5. Install Colossul custom nodes into the shared ComfyUI
#
# custom_nodes and models are intentionally shared: every seat runs the same
# node pack against the same weights. Only per-seat runtime dirs are split.
# ─────────────────────────────────────────────────────────────────────────────
CUSTOM_NODES="$COMFYUI_HOME/custom_nodes"
mkdir -p "$CUSTOM_NODES"

# ── Upgrade ComfyUI itself ──────────────────────────────────────────────────
# The base image pins an older ComfyUI than newer model families need (Minimax
# H3, LTX, Wan Animate 2 all landed after it). COMFYUI_REF selects what to run:
# a branch for latest, or a tag/commit to pin production. Empty = leave the
# image's version untouched.
COMFYUI_REF="${COMFYUI_REF:-master}"
if [ -n "$COMFYUI_REF" ] && [ -d "$COMFYUI_HOME/.git" ]; then
    before="$(git -C "$COMFYUI_HOME" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    log "Updating ComfyUI to '$COMFYUI_REF' (currently $before)..."
    if git -C "$COMFYUI_HOME" fetch --depth 1 origin "$COMFYUI_REF" >/dev/null 2>&1 \
       && git -C "$COMFYUI_HOME" reset --hard -q FETCH_HEAD; then
        after="$(git -C "$COMFYUI_HOME" rev-parse --short HEAD)"
        ver="$(sed -n 's/^__version__ = "\(.*\)"/\1/p' "$COMFYUI_HOME/comfyui_version.py" 2>/dev/null)"
        if [ "$before" = "$after" ]; then
            log "  ComfyUI already current at $after${ver:+ (v$ver)}"
        else
            log "  ComfyUI updated $before -> $after${ver:+ (v$ver)}"
        fi
    else
        warn "  Could not fetch '$COMFYUI_REF' — staying on $before."
        warn "  Check COMFYUI_REF names a real branch/tag/commit."
    fi
elif [ -n "$COMFYUI_REF" ]; then
    warn "$COMFYUI_HOME is not a git checkout — cannot honour COMFYUI_REF=$COMFYUI_REF."
fi

# The stock launcher re-syncs ComfyUI's own requirements on every non-first
# boot (its frontend package drifts after a Manager update). We do it once here
# instead of in each seat wrapper, where four concurrent pip installs into one
# shared venv would race. Mandatory after an upgrade, which usually moves the
# pinned comfyui-frontend-package.
if [ "${SKIP_COMFYUI_REQS:-0}" != "1" ] && [ -f "$COMFYUI_HOME/requirements.txt" ]; then
    log "Syncing ComfyUI requirements (shared venv)..."
    ( cd "$COMFYUI_HOME" && uv pip install --python "$COMFYUI_PYTHON" \
        --no-cache-dir -r requirements.txt ) \
        || warn "ComfyUI requirement sync failed — the UI may be out of step with the backend."
fi

# ── Custom nodes (Colossul + the manifest) ──────────────────────────────────
# Delegated so an operator can re-run it alone after editing custom-nodes.txt,
# without a full re-provision: colossul-seats nodes
log "Installing custom nodes..."
"${COLOSSUL_LIB}/install-custom-nodes.sh" \
    || warn "Custom node installation reported problems — see above."

VNCCS_VENDOR="$BACKEND_DIR/vendor/vnccs_utils"
if [ -d "$VNCCS_VENDOR" ] && [ -n "$(ls -A "$VNCCS_VENDOR" 2>/dev/null)" ]; then
    VNCCS_LINK="$CUSTOM_NODES/ComfyUI_VNCCS_Utils"
    rm -rf "$VNCCS_LINK"
    ln -s "$VNCCS_VENDOR" "$VNCCS_LINK"
    log "Linked VNCCS_Utils -> $VNCCS_LINK"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Shared model store
#
# Every seat reads one model tree, so a 40 GB checkpoint is stored once no
# matter how many seats run. It lives outside the ComfyUI install so an upgrade
# or reinstall of ComfyUI cannot disturb the weights.
#
# This is additive: ComfyUI still scans its own models/ dir, so anything already
# there (the base image symlinks SD1.5 in) keeps resolving.
# ─────────────────────────────────────────────────────────────────────────────
log "Preparing the shared model store at $ASSETS_ROOT ..."
ensure_asset_dirs
write_extra_model_paths "$COLOSSUL_ETC/extra_model_paths.yaml"
log "  wrote $COLOSSUL_ETC/extra_model_paths.yaml ($(( ${#COMFYUI_FOLDER_MAP[@]} )) folder types)"

# An operator-authored file in the store is passed alongside the generated one.
# ComfyUI's --extra-model-paths-config appends, so both apply, and this one is
# never overwritten by provisioning.
if [ -f "$ASSETS_ROOT/extra_model_paths.yaml" ]; then
    log "  also loading operator config: $ASSETS_ROOT/extra_model_paths.yaml"
fi

# Model weights are NOT downloaded here — see section 8, where a supervisor job
# fetches them behind the running seats. Downloading hundreds of gigabytes
# inline would hold every artist off the instance for an hour for something
# ComfyUI does not need in order to start.

# ─────────────────────────────────────────────────────────────────────────────
# 7. Per-seat data directories
# ─────────────────────────────────────────────────────────────────────────────
log "Creating per-seat data directories under $SEATS_DIR ..."
for ((i = 0; i < SEAT_COUNT; i++)); do
    d="$(seat_dir "$i")"
    mkdir -p "$d/comfyui/input" "$d/comfyui/output" "$d/comfyui/temp" "$d/comfyui/user" \
             "$d/backend/outputs"
done

# ─────────────────────────────────────────────────────────────────────────────
# 8. Generate supervisor seat units
#
# Removing the old files first means lowering NUM_SEATS actually retires the
# surplus seats — `supervisorctl update` drops programs whose config vanished.
# ─────────────────────────────────────────────────────────────────────────────
log "Generating supervisor units..."
# Were seats already registered? Distinguishes first boot (update will start
# them) from a re-provision (update leaves identical configs alone).
SEATS_EXISTED=0
compgen -G "/etc/supervisor/conf.d/colossul-seat*.conf" >/dev/null && SEATS_EXISTED=1
rm -f /etc/supervisor/conf.d/colossul-seat*.conf

for ((i = 0; i < SEAT_COUNT; i++)); do
    write_seat_unit "$i" "/etc/supervisor/conf.d/colossul-seat${i}.conf"
done

# Model downloads run as their own job, started with the seats rather than
# before them. Weights arrive while artists are already working.
rm -f /etc/supervisor/conf.d/colossul-models.conf
if [ -n "${MODEL_SETS:-}" ]; then
    write_models_unit /etc/supervisor/conf.d/colossul-models.conf "$MODEL_SETS"
    log "  model downloads queued as a background job: $MODEL_SETS"
    log "  (seats do not wait for it; follow with: colossul-seats models-log)"
else
    log "  MODEL_SETS is empty — no weights will be downloaded."
    log "  (set it in the template's Docker Options, e.g. -e MODEL_SETS=all)"
fi

log "Reloading supervisor..."
# Reachability probe MUST be `supervisorctl pid` (or `version`), never `status`.
# `supervisorctl status` exits NON-ZERO whenever ANY managed program is not
# RUNNING — and the base image's pyworker/syncthing/tensorboard are one-shots
# that exit 0 within seconds of boot — so gating on it aborts provisioning on a
# perfectly healthy instance, right before the seats start. `pid` returns the
# daemon PID and exits 0 whenever the daemon itself is up, regardless of program
# states. (This exact bug ate provisioning on the first instance that got here.)
if ! supervisorctl pid >/dev/null 2>&1; then
    die "supervisord is not reachable, so the seat units cannot be started.
       Inside a running instance this should never happen; if you ran this
       script manually outside the container, start supervisord first."
fi
# Guarded so a transient hiccup here can't abort before the seats are started
# and the access summary is printed.
supervisorctl reread || warn "supervisorctl reread reported an error — continuing."
supervisorctl update || warn "supervisorctl update reported an error — if a seat is missing, run: colossul-seats restart all"

# `supervisorctl update` only (re)starts programs whose CONFIG changed. After a
# source update the configs are identical, so without this the seats would keep
# serving the old build and `colossul-seats provision` would look like it worked
# while changing nothing.
if [ "$SEATS_EXISTED" = "1" ] && [ "$NEED_BUILD" = "1" ]; then
    log "New build — restarting seats so they pick it up..."
    for ((i = 0; i < SEAT_COUNT; i++)); do
        supervisorctl restart "seat${i}:*" >/dev/null 2>&1 \
            || warn "seat $i did not restart cleanly — check: colossul-seats logs $i"
    done
fi

# ─────────────────────────────────────────────────────────────────────────────
# 9. Summary
# ─────────────────────────────────────────────────────────────────────────────
echo ""
log "=============================================================="
log " Seats are the LAST thing to start."
log " Until the READY block appears below, every seat URL will show"
log " a spinner — Caddy and the tunnels are live from boot, but"
log " there is nothing listening behind them yet. This is normal."
log "=============================================================="
log "Waiting for $SEAT_COUNT seat(s) to come up..."

# Wait for the seats, and give Cloudflare a moment to hand out tunnel URLs, so
# the summary below reports what is actually true. Both are bounded: a stuck
# seat or a rate-limited tunnel must not stop the operator getting their links.
if wait_for_seats "$SEAT_COUNT" 150; then
    log "All seats are running."
else
    warn "Not every seat reached RUNNING in time — the summary may be incomplete."
    warn "Check with: colossul-seats status    (and: colossul-seats logs <n>)"
fi

# Tunnels are created asynchronously after each portal entry appears.
for _ in 1 2 3 4 5 6 7 8 9 10; do
    [ -n "$(tunnel_map)" ] && break
    sleep 5
done

seat_status_lines | sed 's/^/[colossul]   /' || true

# LAST thing in the log, deliberately: everything needed to start work.
# Also written to /var/log/portal/ACCESS.log so it has a permanent, findable
# home in the Instance Portal's log viewer rather than only scrolling past.
print_access_summary "$SEAT_COUNT" | access_log_tee
